//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHOM20_DATN.pages.Doctor
{


    public partial class Cap_Nhat_Ho_So_Benh_An
    {
    }
}
